AWSTemplateFormatVersion: 2010-09-09
Description: Cloud formation for Guardian Audio lambda
Parameters:
  Stack:
    Description: Stack name
    Type: String
    Default: mobile
  App:
    Description: Application name
    Type: String
    Default: function-audio-generator
  Stage:
    Description: Stage name
    Type: String
    AllowedValues:
      - CODE
      - PROD
    Default: CODE
  DeployBucket:
    Description: Bucket where RiffRaff uploads artifacts on deploy
    Type: String
    Default: mobile-apps-api-dist
Resources:
  ExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: logs
          PolicyDocument:
            Statement:
              Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: arn:aws:logs:*:*:*
        - PolicyName: lambda
          PolicyDocument:
            Statement:
              Effect: Allow
              Action:
                - lambda:InvokeFunction
              Resource: "*"
        - PolicyName: conf
          PolicyDocument:
            Statement:
              Effect: Allow
              Action:
                - ssm:GetParametersByPath
              Resource: !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/mobile/guardian-audio/${Stage}
        - PolicyName: dynamo-access
          PolicyDocument:
            Statement:
              Effect: Allow
              Action:
                - dynamodb:*
              Resource:
                - !Sub arn:aws:dynamodb:eu-west-1:201359054765:table/guardian-audio-${Stage}
                - !Sub arn:aws:dynamodb:eu-west-1:201359054765:table/guardian-audio-${Stage}/index/*
        - PolicyName: polly
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - polly:*
                Resource: "*"
              - Effect: Allow
                Action: 
                  - s3:PutObject
                  - s3:PutObjectAcl
                Resource:
                  - !Sub arn:aws:s3:::mobile-guardian-audio-${Stage}/*
              - Effect: Allow
                Action: 
                  - sns:Publish
                Resource: 
                  - !Sub arn:aws:sns:${AWS::Region}:${AWS::AccountId}:mobile-guardian-audio-code
  Lambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub ${App}-${Stage}
      Code:
        S3Bucket:
          Ref: DeployBucket
        S3Key: !Sub ${Stack}/${Stage}/${App}/function-audio-generator.zip
      Environment:
        Variables:
          Stage: !Ref Stage
          Stack: !Ref Stack
          App: !Ref App
      Description: Guardian Audio Lambda
      Handler: index.handler
      MemorySize: 128
      Role: !GetAtt ExecutionRole.Arn
      Runtime: nodejs16.x
      Timeout: 60

  DailyEvent:
    Type: AWS::Events::Rule
    Properties:
      Description: Event sent to process the previous day of data
      ScheduleExpression: cron(14 3 * * ? *)
      Targets:
        - Id: Lambda
          Arn: !GetAtt Lambda.Arn

  DailyEventLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt Lambda.Arn
      Principal: events.amazonaws.com
      SourceArn: !GetAtt DailyEvent.Arn